spring:
  application:
    name: caicai
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  ai:
    vectorstore:
      pgvector:
        dimensions: 768
    ollama:
      base-url: http://localhost:11434
      chat:
        model: wangshenzhi/llama3-8b-chinese-chat-ollama-q8:latest
        options:
          temperature: 0.7
      embedding:
        enabled: true
        model: nomic-embed-text
    swagger:
      enabled: true
    api-docs:
      enabled: true
      path: /v3/api-docs
    swagger-ui:
      enabled: true
      persistent-authorization: true
      path: /swagger-ui/index.html
      tags-sorter: alpha
      operations-sorter: alpha
  threads:
    virtual:
      enabled: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB
      file-size-threshold: 0
      location: upload/
caicai:
  media:
    path: ${user.dir}/media/upload/





